resource-server-url: ${RESOURCE_SERVER_URL}
webclient-log-level: INFO

server:
  port: ${PORT:8080}

management: # Actuator
  server:
    port: 8081

springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger

spring:
  application:
    name: "java-spring-oauth2-client"
  security:
    oauth2:
      client:
        provider:
          stackcanary:
            token-uri: ${ISSUER_URL}
        registration:
          stackcanary:
            clientId: ${CLIENT_ID}
            clientSecret: ${CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope:
              - employee.read
              - employee.edit
              - employee.create
              - employee.delete