spring:
  application:
    name: "java-spring-oauth2-client"
  security:
    oauth2:
      client:
        provider:
          stackcanary:
            token-uri: ${ISSUER_URL:http://localhost:9000/oauth2/token}
        registration:
          stackcanary:
            clientId: ${CLIENT_ID:stackcanary-client}
            clientSecret: ${CLIENT_SECRET:hunter2}
            authorization-grant-type: client_credentials
            scope:
              - employee.read
              - employee.edit
              - employee.create
              - employee.delete


resource-server-url: ${RESOURCE_SERVER_URL:"http://localhost:8081"}
webclient-log-level: INFO

server:
  port: ${PORT:8080}
